### ISSUE TITLE
Unable to detect keyword more than 17 times

### ISSUE THREAD

**Issue by decahedron1** [mathquis/node-personal-wakeword#4]
It seems that node-personal-wakeword doesn't want to detect a keyword more than 17 times. I have it hooked up to Discord.js, an API for interacting with [Discord](discord.com). It gives me a 48KHz stereo audio stream which I use `node-libsamplerate` to resample to 16KHz/mono. (Also, Discord only gives audio when the user is speaking; the audio stream isn't continuous and doesn't have silence, not sure if that has anything to do with it). Everything works fine, except if it detects the wakeword more than 17 times, it completely stops detecting wakewords.

Code (the wakeword bit anyways):
```ts
// manual ending ensures the stream doesn't stop when the user stops speaking
const audioStream = connection.receiver.createStream(user, { mode: 'pcm', end: 'manual' });
const resampler = new Resample({
	type: Resample.SRC_SINC_MEDIUM_QUALITY,
	channels: 1,
	fromRate: 48000,
	fromDepth: 16,
	toRate: 16000,
	toDepth: 16
});
resampler.setRatio((1 / 3) / 2);

const detector = new WakewordDetector({
	threshold: 0.1
});

const numSamples = 9;
const samplePaths = [];
for (let i = 1; i <= numSamples; i++)
	samplePaths.push(resolve(__dirname, `../../samples/${i}.wav`));

detector.addKeyword('test', samplePaths, {
	disableAveraging: true,
	threshold: 0.1
}).then(() => {
	detector.on('keyword', ({ keyword, score }) => {
		console.log(`Detected ${keyword}, score ${score}`);
		//(<VoiceChannel>vc).leave();
		//client.destroy();
		//process.exit(0);
	});

	audioStream.pipe(resampler).pipe(detector);
});
```

Logs from multiple runs (the entire output before stopping the program):
![Log 1](http://i.pyke.io/gDjjL.png)
![Log 2](http://i.pyke.io/sFWLU.png)
![Log 3](http://i.pyke.io/Tae8g.png)

**Comment by mathquis** [comment]
I have indeed seen that the detection kind of stop/crash after a while but never manage to find the cause.

I suspect my native binding of the Gist library (used in the features extractor) to crash silently (I’m no C++ dev so I might have done something wrong).

Is it always after the keyword is detected 17 times (why this magic number in your case?) or after a specific time period? 

Also, are you using the latest NPM release or the GitHub master?

**Comment by johanneskropf** [comment]
That looks similar to the issue i encountered with node-red-contrib-personal-wakeword.
Can you confirm at which point it fails silently @sudo-carson ?
For me its always after a detection where it than never returns to the ready state.
I worked around this right now by adding a timeout after a keyword detection that restarts the detector shouldn’t it return to the ready state within a few seconds.

**Comment by mathquis** [comment]
I am unable to reproduce this.

I've been running `sox` for audio capture for 80min+ without issue (more than 4K detections).

```
Buffering...
10/02/2021 à 11:18:28 - Keyword detected: test (score: 0.23 / 0.1, num: 1)
10/02/2021 à 11:18:30 - Keyword detected: test (score: 0.235 / 0.1, num: 2)
10/02/2021 à 11:18:31 - Keyword detected: test (score: 0.247 / 0.1, num: 3)
10/02/2021 à 11:18:32 - Keyword detected: test (score: 0.269 / 0.1, num: 4)
10/02/2021 à 11:18:33 - Keyword detected: test (score: 0.229 / 0.1, num: 5)
...
10/02/2021 à 12:42:46 - Keyword detected: test (score: 0.304 / 0.1, num: 4678)
10/02/2021 à 12:42:47 - Keyword detected: test (score: 0.218 / 0.1, num: 4679)
10/02/2021 à 12:42:48 - Keyword detected: test (score: 0.21 / 0.1, num: 4680)
10/02/2021 à 12:42:49 - Keyword detected: test (score: 0.269 / 0.1, num: 4681)
10/02/2021 à 12:42:49 - Keyword detected: test (score: 0.245 / 0.1, num: 4682)
```

Maybe this is due to some changes since the 1.0.10 release... I'll test it a bit more and release an updated version if everything is good.

**Comment by decahedron1** [comment]
I've confirmed it's not a specific time period; it's always specifically after 17 times. I'm using the latest npm release, 1.0.10. Tried adding `detector.reset()` after the keyword was detected but that didn't change anything (Not actually sure how to restart the detector, but calling that method seemed the most plausible to me, so if I made a mistake please let me know).

I'll try switching around the version and seeing if that helps.

**Comment by decahedron1** [comment]
Downgrading to 1.0.9 and using the master branch both still stopped detecting after 17 times.

**Comment by mathquis** [comment]
This is so weird... There is absolutely no reason for the detector to hang after 17 detections. I'm currently running it since a few hours and have detected the keyword more than 10.000 times with no issue.

I've released a new version with the latest changes on NPM (1.0.11).

@sudo-carson Can you add event handlers (`error`, `close`) to the `audioStream`, `resampler` and `detector` streams?

Also what version of Node and OS are you running?

**Comment by decahedron1** [comment]
Updated to 1.0.11, still the same problem. Added event listeners (code below), no output from any of them.

Running Node 13.9.0 on Windows 10.1909.

```ts
const audioStream = connection.receiver.createStream(user, { mode: 'pcm', end: 'manual' });
const resampler = new Resample({
	type: Resample.SRC_SINC_MEDIUM_QUALITY,
	channels: 1,
	fromRate: 48000,
	fromDepth: 16,
	toRate: 16000,
	toDepth: 16
});
resampler.on('error', e => {
	console.log('Resampler error', e);
});
resampler.on('close', () => {
	console.log('Resampler close');
});
resampler.setRatio((1 / 3) / 2);

const detector = new WakewordDetector({
	threshold: 0.1
});

const numSamples = 9;
const samplePaths = [];
for (let i = 1; i <= numSamples; i++)
	samplePaths.push(resolve(__dirname, `../../samples/${i}.wav`));

detector.addKeyword('test', samplePaths, {
	disableAveraging: true,
	threshold: 0.1
}).then(() => {
	console.log('loaded samples');

	detector.on('keyword', ({ keyword, score }) => {
		console.log(`Detected ${keyword}, score ${score}`);
		//(<VoiceChannel>vc).leave();
		//client.destroy();
		//process.exit(0);
	});

	detector.on('error', e => {
		console.log('Detector error', e);
	});

	detector.on('close', () => {
		console.log('Detector close');
	});

	audioStream.on('error', e => {
		console.log('Discord error', e);
	});

	audioStream.on('close', () => {
		console.log('Discord close');
	});

	audioStream.pipe(resampler).pipe(detector);
});
```

**Comment by mathquis** [comment]
I think your issue might comes from Discord.js... Maybe:
https://github.com/discordjs/discord.js/issues/4161#issuecomment-623680248

Can you try without the detector at all to see if you can get the `audioStream` from Discord into a file or something? Or use a `data` event handler with `console.log` on the `audioStream` to see if it also stops after a few seconds (17?).

**Comment by decahedron1** [comment]
Opus silence packet was already added, I just didn't add it to the snippet, sorry.

Ran it straight into a raw audio stream file. All was good, until a few seconds later the program stopped. The audio file was only 23.837 seconds in length, which means somehow, either `node-libsamplerate` or Discord.js is silently crashing, and *somehow*, `node-personal-wakeword` is preventing the program from stopping entirely?

Removing the resampler fixed it... the audio is sped up for some reason (but that's not as big of a deal as losing the resampler), but other than that I can run it for as long as I want.

`node-libsamplerate` hasn't been updated in 2 years so I'm afraid I won't have much luck opening an issue over there, so I guess I'll have to try to fix it myself :confused:

Thanks for the help!

**Comment by mathquis** [comment]
Try removing this: `resampler.setRatio((1 / 3) / 2);`

**Comment by decahedron1** [comment]
Removing that didn't fix the issue, still stops after 25.619 seconds. Tried looking for memory leaks, found nothing; memory usage never went past 90 MB (including PowerShell's memory consumption).

**Comment by mathquis** [comment]
It was worth a shot :) . Good luck!

**Comment by decahedron1** [comment]
Fixed it!

I was lying to `node-libsamplerate` by saying there was only 1 channel (when there was 2); my thought was that if I play it back at 2x speed, it would skip over one of the channels. For the most part, it worked, until it didn't. The audio was just fine, but for some reason, libsamplerate doesn't like it when I lie to it. So I changed it to stereo and added this piece of code from [here](https://refruity.xyz/writing-discord-bot/):

```ts
function convertBufferTo1Channel(buffer) {
	const convertedBuffer = Buffer.alloc(buffer.length / 2);

	for (let i = 0; i < convertedBuffer.length / 2; i++) {
		const uint16 = buffer.readUInt16LE(i * 4);
		convertedBuffer.writeUInt16LE(uint16, i * 2);
	}

	return convertedBuffer;
}

class ConvertTo1ChannelStream extends Transform {
	constructor(source, options) {
		super(options);
	}

	_transform(data, encoding, next) {
		next(null, convertBufferTo1Channel(data));
	}
}
```

I piped the resampled data into that stream, then into the file write stream/`node-personal-wakeword`, and it worked flawlessy! Didn't need any hacky speed changes (don't ask why the 1/3 was there too, because I don't know, but it worked at the time).

There was a memory leak issue (110+ MB when talking for 30 seconds!), so I ended up having to use [nanokina's fork](https://github.com/nanokina/node-libsamplerate), which brought my memory usage down to about ~20 MB after talking for 2 or so minutes.

**Comment by Baael** [comment]
hi, great library! I really like it. 
However I have exactly same issue - after few detections it hangs (at least on windows). I wasn't able to track why and where it happen, may it be related to gist library?

EDIT: on linux too

**Comment by mathquis** [comment]
@Baael

Gist is pretty passive. It processes the audio frames on demand.

I've been running the detector for hours on my desktop computer and a Raspberry Pi 3B+ without issue.

What are you using to capture the audio data?

How do you feed the audio data to the detector (stream pipe, process method)?

**Comment by Baael** [comment]
@mathquis 
Hello.
I am using spawned sox, data are retrieved even after detector hangs out, so I guess it isn't an issue
```sox -t waveaudio default -b 16 --endian little -c 1 -r 16000 -e signed-integer -t wav -```

I tried to use 
```js
sox.stdout.pipe(detector)
``` 

and

```js
sox.stdout.on('data', buffer => {
   detector.write(buffer)
})
``` 

I've tried to mimic microphone input with prerecorded files and even stream microphone to rpi and linux machine. In all cases it hangs after few detections, but only after detections, without triggering keywords it works for hours.

**Comment by mathquis** [comment]
@Baael I've added debug logs (with the `debug` NPM module).

Can you do a test run using the `master` branch with `DEBUG=*`?

I'd be mostly interested in the startup output and the logs when the detection starts to become unresponsive.

Thanks.

PS: I'm also on Windows using Sox. Here are my command line args:
`sox --no-show-progress --buffer 960 --channels 1 --endian little --bits 16 --rate 16000 --default-device --type raw -`

PS2: Do you have some kind of AGC enabled on your mic? I've noticed that AGC often seems to decrease detection accuracy.

**Comment by mathquis** [comment]
@Baael @sudo-carson @johanneskropf

Finally some progress!

I found why the detector stops after a while. It is indeed after 16 detections.

This is caused by the detector readable stream high watermark (16 by default).

If you do not pipe the detector stream and rely on events, you need to consume the `data` event otherwise the data fills the detector readable stream buffer and pause.

To avoid future issues, I will remove the `keyword` event in the next release and only keep the `data` event. This may break stuffs.

Cheers.
